#alertmanager.yml

#global config
global:
  resolve_timeout: 30s
  slack_api_url: 'YOUR WEBHOOK URL'
route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
