#permissions.yml

--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: 
  name: prometheus-kube
rules: 
- apiGroups:
    - ""
  resources: 
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
    - extensions
  resources: 
    - ingresses
  verbs: 
    - get
    - list
    - watch
- nonResourceURLs: 
    - /metrics
  verbs: 
    - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-kube
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: default
